### PR TITLE
Domain lock feature

### PR DESCRIPTION
**Pull request by slig**
Hi!

Thanks for accepting this PR! I made the changes you proposed on the issue #12.

Few issues/questions:

* When passing the domainLock option to the CLI, if the domain starts with a dot (meaning accept any subdomain from that domain), the dot needs to be escaped (e.g. --domainLock=\\.example.com) otherwise it doesn't work because the option is not recognized. Not sure if this can be improved;
* On my first commit I accidentally included my updated tsconfig.json on that commit. (I had to change it because Atom was compiling every file I saved and it was polluting the workspace with .js files).
* I hid the "throw new Error" within a eval. Is this the best way to hide it? (Maybe we can use the same RegExp mechanism here, so it doesn't became evident when using a pretty print tool like closure compiler.);
* Every other custom Node is within two directories, this one isn't.

Thank you very much!

### CODE REVIEW

**Comment by sanex3339** [comment]
`domainLock=\.example.com`

if i remember correctly, in that case it must be like
`--domainLock='.example.com'`

**Comment by sanex3339** [comment]
it looks like there errors during build, but build status is ok. I trying to fix that, so build will fail on typescript errors.

**Comment by slig** [comment]
That's weird. Here all the tests are passing and the coverage isn't that low.

> Statements   : 92.19% ( 767/832 )
> Branches     : 89.66% ( 234/261 )
> Functions    : 82.86% ( 58/70 )
> Lines        : 92.48% ( 763/825 )

**Comment by sanex3339** [comment]
i will merge PR to dev and look into that, thank you again

**Comment by sanex3339** [comment]
`startsWith` and `endsWith` is not good solution because bad browsers support:
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith

**Comment by slig** [comment]
You're right!

I found this snippet:

`function endsWith(str, suffix) {
    if (str.length < suffix.length)
        return false;
    return str.lastIndexOf(suffix) === str.length - suffix.length;
}`

If you've not merged yet, I can update the code.

**Comment by sanex3339** [comment]
i updated it locally

**Comment by sanex3339** [comment]
i merged it into `dev` branch. All continuous fixes must be based on `dev` branch.

**Pull request closed without merging**
